from collections.abc import Callable
from typing import Protocol
from uuid import UUID

from app.domain.entities import Assessment, Brief, Proposal, Task, Team, User


class Repository(Protocol):
    async def ping(self) -> None: ...
    async def user(self, user_id: UUID) -> User | None: ...
    async def users(self) -> list[User]: ...
    async def skills(self) -> list[dict]: ...
    async def validate_skills(self, slugs: list[str]) -> None: ...
    async def task(self, task_id: UUID, lock: bool = False) -> Task | None: ...
    async def save_task(self, task: Task) -> None: ...
    async def tasks(
        self,
        *,
        owner: UUID | None = None,
        limit: int = 20,
        offset: int = 0,
        sort: str = "quality",
        skill: str | None = None,
        q: str | None = None,
    ) -> tuple[list[Task], int]: ...
    async def add_score(self, task: Task, reason: str) -> None: ...
    async def history(self, task_id: UUID) -> list[dict]: ...
    async def add_answer(self, task_id: UUID, field: str, answer: str) -> None: ...
    async def team(self, team_id: UUID) -> Team | None: ...
    async def teams(self, user_id: UUID) -> list[Team]: ...
    async def save_team(self, team: Team) -> None: ...
    async def proposal(self, proposal_id: UUID) -> Proposal | None: ...
    async def proposals(
        self,
        *,
        task_id: UUID | None = None,
        member_id: UUID | None = None,
        limit: int = 20,
        offset: int = 0,
    ) -> tuple[list[Proposal], int]: ...
    async def has_proposal(self, task_id: UUID, team_id: UUID) -> bool: ...
    async def save_proposal(self, proposal: Proposal) -> None: ...
    async def select_proposal(self, proposal: Proposal) -> None: ...


class UnitOfWork(Protocol):
    repo: Repository

    async def __aenter__(self) -> "UnitOfWork": ...
    async def __aexit__(self, *args) -> None: ...
    async def commit(self) -> None: ...


UnitOfWorkFactory = Callable[[], UnitOfWork]


class Analyzer(Protocol):
    async def analyze(
        self, raw_text: str, brief: Brief, improve: bool
    ) -> tuple[Brief, Assessment]: ...
