"""accounts_sessions_and_teams

Revision ID: dabbc2819b60
Revises: c628a2698949
"""

import sqlalchemy as sa

from alembic import op

revision = "dabbc2819b60"
down_revision = "c628a2698949"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rate_limits",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("resets_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_rate_limits")),
    )
    op.create_index(op.f("ix_rate_limits_resets_at"), "rate_limits", ["resets_at"], unique=False)
    op.create_table(
        "auth_sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_auth_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("token_hash", name=op.f("pk_auth_sessions")),
    )
    op.create_index(
        op.f("ix_auth_sessions_expires_at"), "auth_sessions", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_auth_sessions_user_id"), "auth_sessions", ["user_id"], unique=False)
    op.create_table(
        "team_invites",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            name=op.f("fk_team_invites_team_id_teams"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("token_hash", name=op.f("pk_team_invites")),
    )
    op.create_index(op.f("ix_team_invites_team_id"), "team_invites", ["team_id"], unique=False)
    op.add_column("teams", sa.Column("owner_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_teams_owner_id_users"), "teams", "users", ["owner_id"], ["id"], ondelete="RESTRICT"
    )
    op.add_column("users", sa.Column("password_hash", sa.String(length=255), nullable=True))
    op.execute(
        "UPDATE teams SET owner_id = (SELECT user_id FROM team_members "
        "WHERE team_members.team_id = teams.id ORDER BY created_at, user_id LIMIT 1)"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password_hash")
    op.drop_constraint(op.f("fk_teams_owner_id_users"), "teams", type_="foreignkey")
    op.drop_column("teams", "owner_id")
    op.drop_index(op.f("ix_team_invites_team_id"), table_name="team_invites")
    op.drop_table("team_invites")
    op.drop_index(op.f("ix_auth_sessions_user_id"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_expires_at"), table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_index(op.f("ix_rate_limits_resets_at"), table_name="rate_limits")
    op.drop_table("rate_limits")
    # ### end Alembic commands ###
