import { test, expect } from '@playwright/test';
const fields=['title','problem','goal','deliverable','success_criteria','target_users','constraints','timeline','resources','risk_context'];
test('AI question and suggestion require consent; review stays readable',async({page})=>{
 let release!: () => void;
 const gate = new Promise<void>(resolve => {release = resolve;});
 await page.route('**/api/v1/tasks/*/interview',async route=>{await gate; return route.fulfill({json:{summary:'Интернет-магазин',source:'openai',warning:null,questions:fields.map(field=>({field,question:field==='problem'?'Что вы продаёте и как принимаете заказы сейчас?':field==='target_users'?'Кто покупает в вашем магазине?':'Как уточнить ваш интернет-магазин?',hint:'Уточним потребность магазина.'}))}});});
 await page.route('**/api/v1/tasks/*/coach',route=>{const body=route.request().postDataJSON();return route.fulfill({json:{question:body.field==='problem'?'Как сейчас продаётся ваша обувь?':'Как назвать ваш интернет-магазин?',hint:'Вопрос с учётом вашего бизнеса.',suggestion:'Интернет-магазин обуви',followups:['Какие товары планируете продавать?'],source:'openai',warning:null,revision:body.expected_revision,field:body.field}});});
 await page.goto('/register');await page.getByLabel('Ваше имя').fill('AI Тест');await page.getByLabel('Email',{exact:true}).fill(`ai-deck-${Date.now()}@example.com`);await page.getByLabel('Пароль',{exact:true}).fill('Interview-test-password-2026');await page.getByRole('button',{name:'Создать аккаунт',exact:true}).click();await page.waitForURL('**/dashboard');
 await page.getByLabel('В чём ваша задача?').fill('Хочу создать интернет-магазин для своего бизнеса');await page.getByRole('button',{name:'Создать черновик',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Готовим вопросы по вашей идее'})).toBeVisible();
 await expect(page.getByRole('textbox')).toHaveCount(0);
 await expect(page.getByText('Как назовём вашу задачу?')).toHaveCount(0);
 await page.screenshot({path:'../artifacts/interview-loading.png'});
 release();
 await expect(page.getByRole('heading',{name:'Что вы продаёте и как принимаете заказы сейчас?'})).toBeVisible();
 await expect(page.getByLabel('Проблема бизнеса *',{exact:true})).toHaveValue('');
 await page.getByRole('button',{name:'Использовать этот ответ'}).click();
 await expect(page.getByRole('heading',{name:'Что вы продаёте и как принимаете заказы сейчас?'})).toBeVisible();
 await page.screenshot({path:'../artifacts/interview-ready.png'});
 await expect(page.getByLabel('Проблема бизнеса *',{exact:true})).toHaveValue('Интернет-магазин обуви');
 await page.getByRole('button',{name:'Далее',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Кто покупает в вашем магазине?'})).toBeVisible();
 await page.getByLabel('Целевая аудитория',{exact:true}).fill('Мой собственный ответ');
 await expect(page.getByRole('button',{name:'Использовать этот ответ'})).toHaveCount(0);
 for(let i=1;i<10;i++)await page.getByRole('button',{name:'Далее',exact:true}).click();
 await page.getByRole('button',{name:'К проверке',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Проверьте вашу задачу'})).toBeVisible();
 await expect(page.getByRole('button',{name:'Описание задачи',exact:true})).toHaveAttribute('aria-pressed','true');
 await expect(page.getByText('Мой собственный ответ',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Оценка AI',exact:true}).click();
 await expect(page.getByText('Нажмите «Оценить задачу»')).toBeVisible();
 await page.setViewportSize({width:390,height:844});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
