import { test, expect } from '@playwright/test';
test('business notification opens proposals and logout returns to role choice',async({page})=>{
 const taskId='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
 const noticeId='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
 let read=false;
 await page.route('**/api/v1/business/notifications?*',route=>route.fulfill({json:{items:[{id:noticeId,task_id:taskId,task_title:'Тестовая задача',team_name:'Команда теста',created_at:new Date().toISOString(),read}],unread_count:read?0:1,total:1}}));
 await page.route(`**/api/v1/business/notifications/${noticeId}/read`,route=>{read=true;return route.fulfill({json:{ok:true}});});
 await page.goto('/login?role=business');
 await page.getByRole('button',{name:'Войти в аккаунт',exact:true}).click();
 await expect(page).toHaveURL(/dashboard/);
 const user=await (await page.request.get('/api/v1/auth/me')).json();
 await page.route(`**/api/v1/tasks/${taskId}`,route=>route.fulfill({json:{id:taskId,business_id:user.id,status:'published',brief:{title:'Тестовая задача',problem:'Проблема',goal:'Цель',deliverable:'Результат',success_criteria:'Критерии',timeline:'Три недели'},skill_slugs:[],quality_score:0,quality_level:'Draft'}}));
 await page.route(`**/api/v1/business/tasks/${taskId}/proposals?*`,route=>route.fulfill({json:{items:[],total:0,limit:10,offset:0}}));
 await page.getByRole('button',{name:'Уведомления: 1 новых'}).click();
 await page.getByRole('button',{name:/Команда теста/}).click();
 await expect(page).toHaveURL(new RegExp(`${taskId}#proposals`));
 expect(read).toBe(true);
 await expect(page.getByRole('heading',{name:'Предложения команд'})).toBeInViewport();
 await page.reload();
 await page.getByRole('button',{name:'Уведомления',exact:true}).click();
 await expect(page.getByRole('button',{name:/Команда теста/})).not.toContainText('Новое');
 await page.setViewportSize({width:390,height:844});
 await expect(page.locator('.notification-panel')).toBeInViewport();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:'../artifacts/notifications-mobile.png',fullPage:true});
 await page.getByRole('button',{name:'Закрыть уведомления'}).click();
 await page.getByRole('button',{name:'Выйти',exact:true}).click();
 await expect(page).toHaveURL('http://localhost:5173/');
 await expect(page.getByRole('heading',{name:'Большие дела начинаются с вас.'})).toBeVisible();
 await page.reload();
 await expect(page).toHaveURL('http://localhost:5173/');
 expect((await page.request.get('/api/v1/auth/me')).status()).toBe(401);
});
