import { test, expect } from '@playwright/test';
test('student onboarding persists skills and recommends complementary teams',async({page})=>{
 await page.goto('/register?role=student');
 await page.getByLabel('Ваше имя').fill('Тест Студент');
 await page.getByLabel('Email',{exact:true}).fill(`student-match-${Date.now()}@example.com`);
 await page.getByLabel('Пароль',{exact:true}).fill('Student-match-password-2026');
 await page.getByRole('button',{name:'Создать аккаунт',exact:true}).click();
 await expect(page).toHaveURL(/student\/profile/);
 await page.getByLabel('Фронтенд',{exact:true}).check();
 await page.getByRole('button',{name:'Далее',exact:true}).click();
 await page.getByLabel('React',{exact:true}).check();
 await page.getByLabel('TypeScript',{exact:true}).check();
 await page.getByRole('button',{name:'Далее',exact:true}).click();
 await page.getByLabel('Есть учебные или личные проекты',{exact:true}).check();
 await page.getByRole('button',{name:'Показать подходящие задачи'}).click();
 await expect(page.getByRole('heading',{name:'Задачи для вас',exact:true})).toBeVisible();
 await expect(page.getByText('Витрина интернет-магазина · демо',{exact:true})).toBeVisible();
 await page.reload();
 await expect(page.getByRole('heading',{name:'Задачи для вас',exact:true})).toBeVisible();
 await page.screenshot({path:'../artifacts/student-matches.png',fullPage:true});
 await page.getByRole('link',{name:'Найти команду',exact:true}).click();
 const card=page.locator('article').filter({has:page.getByRole('heading',{name:'API Crew · демо',exact:true})});
 await expect(card.locator('p').filter({hasText:'Вы добавите:'})).toContainText('react');
 await card.getByRole('button',{name:'Вступить в команду'}).click();
 await expect(card).toHaveCount(0);
 await expect(page.getByRole('link').filter({has:page.getByRole('heading',{name:'API Crew · демо',exact:true})})).toBeVisible();
 await page.setViewportSize({width:390,height:844});
 await expect(page.locator('.sidebar')).toBeHidden();
 await page.getByRole('button',{name:'Открыть меню'}).click();
 await expect(page.locator('.sidebar')).toBeVisible();
 await page.getByRole('button',{name:'Закрыть меню'}).click();
 await expect(page.locator('.sidebar')).toBeHidden();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:'../artifacts/student-teams-mobile.png',fullPage:true});
});
